### ISSUE TITLE
how do you triain on celeba-hq?

### ISSUE THREAD

**Issue by thinkerthinker** [elvisyjlin/AttGAN-PyTorch#5]
when i train attgan on celeba-hq, I found the loss is very strange, for example,
 39%|▍| 684/1750 [26:59<39:02,  2.20s/it, d_loss=3.62e+10, epoch=0, g_loss=5.11e+5, iter=684] 
by visualizing the curves of loss, df_gp, df_loss, g_loss, gf_loss is very high, and they still increases. 
Are you re-adjusting the coefficients of each loss?  Or what tricks did you use?

**Comment by elvisyjlin** [comment]
Here is my training history on CelebA-HQ 256x256 (`256_shortcut1_inject1_none_hq`):

<img width="975" alt="screen shot 2019-03-07 at 2 08 49 pm" src="https://user-images.githubusercontent.com/10172439/53935789-a7972d80-40e2-11e9-8768-da796af009d0.png">
<img width="975" alt="screen shot 2019-03-07 at 2 09 15 pm" src="https://user-images.githubusercontent.com/10172439/53935798-aebe3b80-40e2-11e9-8037-2e6d722ef01b.png">

At the first several hundred steps, d_loss was very small (negative) whilst g_loss started from a very large value (positive). Apparently, they _converged at about 5k steps_. I trained this model, the one you can download from the Google Drive, with __the default setting__ in the readme.

```bash
CUDA_VISIBLE_DEVICES=0 python3 train.py --data CelebA-HQ --img_size 256 --shortcut_layers 1 --inject_layers 1 --experiment_name 256_shortcut1_inject1_none_hq --gpu
```

What is your training setting? How does your training history look like?

**Comment by thinkerthinker** [comment]
Thank you. I found that the loss divergence was caused by the use of multiple gpu. If I only use one gpu, the training process is correct. I think I might be having problems with Dataparallel。

**Comment by elvisyjlin** [comment]
Thank you, too. You reminded me the multi GPU problem which I also encountered recently.

Briefly speaking, the autograd to compute gradient penalty is accidently deleted when the function `gradient_penalty()` is returned. This is a bug since PyTorch 1.0.0 released. See [this issue](https://github.com/pytorch/pytorch/issues/16532).

You can try multi GPU training with the code I fixed just now.

**Comment by thinkerthinker** [comment]
Your answer has helped me a lot, thank you again for your reply.

**Comment by elvisyjlin** [comment]
You're welcome ^^

**Comment by thinkerthinker** [comment]
I still have a problem with multi_gpu. I am running your modified code, but there are some issues in zs_a = self.G.encode(img_a): AttributeError: 'DataParallel' object has no attribute 'encode'. When I changed zs_a = self.G.encode(img_a) to zs_a = self.G.**module**.encode(img_a) , the code can run but the loss is diverging. I don't know where I made the mistake.
